### ISSUE TITLE
Incorrect image files extension in zip files from Mangapark

### ISSUE THREAD

**Issue by janfett** [darkdragn/mangaGet2#2]
The images in the .cbz files created from Mangapark have incorrect extensions in some cases. E.g. the filename is _001.jpg?14325240978_ instead of just _001.jpg_. This leads comic book readers being unable to read and display images. 

This does not happen all the time, but certainly happens for some series (it happened to me repeatedly with _boku to issho_). Should also mention I am running this on Linux. '?' might be an invalid character for filenames in Windows (not so sure), so this problem might never occur.

**Comment by darkdragn** [comment]
Rgr, I'll look in to it when I get off of work. Mind if I get a chapter
number for Boku to Issho that you were getting the error on, so I have a
starting point for when I get home?

**Comment by janfett** [comment]
Thanks. This problem occurred even with Chapter 1. On another note, it seems to have arisen from the latest commit.

**Comment by darkdragn** [comment]
Sorry it took a little bit, but the commit fixing this is up now. I had been doing some parsing of the name too early/ in the wrong place. Instead of it occuring with the naming def, I had it up in the chapter class, before the url was even passed to page, so I didn't notice it had messed up the naming convention later when I took it out. 

Give it a test and let me know how it's working.
